# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ray Santos 
tagline:          
url:              http://raywritescode.github.io
paginate:         1
baseurl:          /
author:
  name:           Ray Santos
  url:            https://twitter.com/raywritescode
  email:          ray@raywritescode.com
pages_list:
  About: '/about'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/raywritescode
