# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ray.writes.code( ) 
tagline:          
url:              http://www.raywritescode.com
paginate:         1
baseurl:          /
author:
  name:           Ray Santos
  url:            https://twitter.com/raywritescode
  email:          ray@raywritescode.com
pages_list:
  About: '/about'
  Archives: '/archives'
  Bookshelf: '/bookshelf'
  Study Log: '/studylog'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/raywritescode
