# Dependencies
markdown:         kramdown
theme:            minima
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ray.writes.code( ) 
tagline:          
url:              http://www.raywritescode.com
paginate:         5
gems:             
    - jekyll-paginate             
  
baseurl:          /
author:
  name:           Ray Santos
  email:          ray@raywritescode.com
pages_list:
  # About: '/about'
  Archives: '/archives'
  Bookshelf: '/bookshelf'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/raywritescode
